<a href="https://colab.research.google.com/github/BilalAhmed7072/Deep-Learning-with-Keras-and-Tensorflow/blob/main/Custom_layers_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Used for new algorithm and techniques,
enhanced flexibility,
optimize performance,
we can create layers according to our need




**Basics of Creating custom layers**

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Layer

# 🔹 Step 1: Define the custom layer
class MyDenseLayer(Layer):
    def __init__(self, units=32):
        """
        Constructor: This is where you define the configuration.
        You don't create weights here, only store configs like 'units'.
        """
        super(MyDenseLayer, self).__init__()  # call parent class constructor
        self.units = units  # number of neurons in this layer

    def build(self, input_shape):
        """
        This method is automatically called the first time the layer is used.
        Here we create the trainable weights using input shape info.
        """
        # input_shape[-1] is the number of features (input neurons)
        self.w = self.add_weight(
            name="kernel",
            shape=(input_shape[-1], self.units),  # [input_dim, output_dim]
            initializer="random_normal",
            trainable=True
        )

        self.b = self.add_weight(
            name="bias",
            shape=(self.units,),  # one bias per output unit
            initializer="zeros",
            trainable=True
        )

    def call(self, inputs):
        """
        Forward pass logic: This is where the layer processes inputs.
        Here we apply: output = inputs * weights + bias
        """
        return tf.matmul(inputs, self.w) + self.b


#  Step 2: Use the custom layer
# Create some sample input data: 1 sample, 3 input features
x = tf.constant([[1.0, 2.0, 3.0]])

# Create an instance of our custom layer with 2 output units
my_layer = MyDenseLayer(units=2)

# Pass input through the layer (this will trigger build() automatically)
output = my_layer(x)

#  Step 3: Print results
print("Input:")
print(x.numpy())

print("\nWeights:")
print(my_layer.w.numpy())

print("\nBias:")
print(my_layer.b.numpy())

print("\nOutput:")
print(output.numpy())


Input:
[[1. 2. 3.]]

Weights:
[[ 0.00969952 -0.06123686]
 [ 0.01403055  0.00922152]
 [-0.0581724  -0.00182037]]

Bias:
[0. 0.]

Output:
[[-0.13675658 -0.04825491]]
